language: python
python:
  - "3.6"
dist: xenial
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off pytest-cov pytest-faulthandler codecov
script:
  - py.test --cov-report=xml --cov=pylat --ignore=examples
after_success:
  - codecov
